version: "3.7"

services:
  redis:
    container_name: redis
    image: library/redis:5.0-alpine
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - net01
    volumes:
      - redis_data:/data

  vsf:
    env_file: ../.env.docker
    build:
      context: ../
      dockerfile: Dockerfile

    container_name: vsf
    ports:
      - 3000:3000
    image: vsf2
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - net01

volumes:
  redis_data:
    external: false

networks:
  net01:
    name: net01
